import './globals.css';
import { Provider } from 'react';

//this layout applies to EVERYTHING!!! you can add the navbar and stuff here haha

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          hey im the nav bar!
        </nav>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
