import './globals.css';
// import { Provider } from 'react';
import Navbar from './navbar';

//this layout applies to EVERYTHING!!! you can add the navbar and stuff here haha

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Navbar />
        </nav>
        {/* <Provider store={store}> */}
        {children}
        {/* </Provider> */}
      </body>
    </html>
  )
}
